### ISSUE TITLE
auth guide is missing

### ISSUE THREAD

**Issue by rcoup** [cogeotiff/www.cogeo.org#21]
The [Providers page](https://github.com/cogeotiff/www.cogeo.org/blob/ef4d669c97459837b3fd996b116ede130b5d3d4d/providers-guide.html#L48) has a link to an Auth guide, but it doesn't appear to exist. Missing checkin?

**Comment by cholmes** [comment]
Sadly it's not a missing checkin. I think I had links for various pieces of content I aspired to complete. Thought I removed all of them before going live, but it appears I forgot this one. Thanks for the catch, will fix.
