### ISSUE TITLE
Add info about twitter account

### ISSUE THREAD

**Issue by cholmes** [cogeotiff/www.cogeo.org#42]
We now have https://twitter.com/cogeotiff

Would be good to have that info on the website, so people can follow.

Maybe one of those social media icon things that has twitter, github, and maybe slack?

**Comment by batugane** [comment]
Added Twitter, GitHub, and Slack icons to the footer with hover effects. See my recent pull request [#66](https://github.com/cogeotiff/www.cogeo.org/pull/66).
