### ISSUE TITLE
Cite that COG is now a OGC standard

### ISSUE THREAD

**Issue by joanma747** [cogeotiff/www.cogeo.org#64]
Please, 

Consider to add to the cogeo.org website that the COG is now an OGC standard: https://www.ogc.org/press-release/cloud-optimized-geotiff-cog-published-as-official-ogc-standard/

It was done respecting carefully the community practices without adding or breaking any of the characteristics specified here.

Please see the standard here: https://docs.ogc.org/is/21-026/21-026.html

I hope we can both continue collaborating in promoting COG.

Thanks,

**Comment by ogcscotts** [comment]
This would be great - thanks, @joanma747

**Comment by cholmes** [comment]
Hey, I'm slammed right now, and I'm the primary maintainer of the site - would you be up to make a pull request? If you can then I can easily review and merge. If I've got to write it myself then it'll take a good bit longer.

thanks!

**Comment by coneypylon** [comment]
I'm not OP, but I put in a PR

**Comment by cholmes** [comment]
Awesome, thanks @coneypylon! I merged yours in. I'm definitely open to more prominent mentions as well. I do think the 'read the spec' button should go to the OGC spec, or at least the ogc repo. And we could perhaps put some OGC logo somewhere.

**Comment by coneypylon** [comment]
It makes sense to me to put the logo on the main page in place of the broken NASA one then, IMO. The spec could get added there as well.
