### ISSUE TITLE
Replace broken nasa logo and put in OGC logo

### ISSUE THREAD

**Issue by cholmes** [cogeotiff/www.cogeo.org#67]
It makes sense to me to put the logo on the main page in place of the broken NASA one then, IMO. The spec could get added there as well.

_Originally posted by @coneypylon in https://github.com/cogeotiff/www.cogeo.org/issues/64#issuecomment-1898594654_

**Comment by batugane** [comment]
I have replaced the broken NASA logo with the OGC logo and added the OGC spec link to the main page. This should address and close issue #67. 

Additionally, issues #41 and #42 can also be closed as they were included in the last pull request of mine.

**Comment by cholmes** [comment]
thank you!
