### ISSUE TITLE
SSL error for HTTPS URL

### ISSUE THREAD

**Issue by fmigneault** [cogeotiff/www.cogeo.org#72]
[`https://cogeo.org`](https://cogeo.org) has been reporting SSL errors for some time now. 
The certificate should be renewed.

This breaks any documentation that performs link-checks against the site.

**Comment by vincentsarago** [comment]
The certificat has expired, @cholmes I'm not sure how to request a new one

**Comment by cholmes** [comment]
Ah, thanks for the reminder. I started to look into this, I thought it was one I owned and I could just fix myself, but I'm pretty sure I had Planet buy it. Meant to dig into figure out how to get them to fix it, but that fell off. Will do so now.

**Comment by cholmes** [comment]
Alright, I think I got this fixed. Let me know if you see more problems.
